### ISSUE TITLE
Issues loading mods

### ISSUE THREAD

**Issue by pgraham1337** [Cambusta/Arma3-SSPSL#1]
I'm having issues loading mods on the server. The console window shows that mods were read, but upon loading a mission on a modded map and getting past the role selection screen, the server throws a "No entry "Bin\config.bin\CfgWorlds.xxx" error. I've tried to set the map mods to both server side and global, and neither has worked. 
I have the map on my client, I can open the editor with no problems.
I checked the !Workshop folder and the map .pbo is still there.
I don't think that any mods are being loaded with the server as modded functions aren't working on vanilla maps.
![sspsl](https://user-images.githubusercontent.com/8490448/93840428-f5886d80-fc55-11ea-984a-5c507c703a3f.PNG)

**Comment by Cambusta** [comment]
Hey @pgraham1337!

Yea, that's weird. Looks like you've got everything set up correctly, the message shouldn't be there.

I'll try to replicate it on my side, could you please clarify if
- Server capable of loading other missions on Bornholm?
- Server capable of loading other missions on other (non-vanilla) maps?
- The name of the mission, if available? If you have a link to it that would be great.

> I've tried to set the map mods to both server side and global, and neither has worked.
Yea, maps should be global at all times (i.e loaded on both client and server). Seems that you got this right though so it's strange that there's an issue.

**Comment by pgraham1337** [comment]
Thanks for the reply!

To answer your question, yes, all addon missions, including the one I tried, loaded.
One thing I have learned from hosting a few private servers here and there is that sometimes you just don't know with Arma.

I was using TADST prior to using SSPSL. TADST could load mods, but would violently cycle missions so fast it would switch missions before you could load in.
Now, it seems SSPSL is doing the opposite: It can't load any mods (ACE functions and maps not loading), but all missions appear as normal and are able to get into the role selection screen, meaning they have correctly been loaded and read.
I think it has something to do with mod pathing. I created a list of my mods and added them as launch parameters manually, and the issue persisted.

However, I since have begun using [`Serverify A3`](https://github.com/igorkis-scrts/Serverify-A3) with no issues. I noticed both TADST and ServerifyA3 use absolute paths for the -mod parameter, ie:
 "-mod=C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@ace;"
I don't understand how this could be any different than what SSPSL does, as it goes into the workshop directory and can read it anyways, but this might be worth looking in to.

**Comment by Cambusta** [comment]
Hey, really appreciate your help! 🙂

Yea, Arma sure can be a one big pitfall at times. To think how many nerves I've waster making missions. 😁

Could you please post server's RPT (log) file? To get one, 

1. Start the server with SSPSL and your mod preset.
2. Load any mission that causes the problem.
3. Once you get an error, close the server window.
4. In SSPSL folder, navigate to `\profiles` subfolder.
5. There will be a bunch of files with the names like `arma3server_x64_2020-08-20_19-12-13.rpt`.
6. Find the newest file among them (sorting the folder by Date is probably the simplest way) and attach it here.

This file should point us in the direction of a problem.

**Comment by Cambusta** [comment]
Speaking of mod paths, you might be onto something. The thing that SSPSL does differently is that it resolves the actual path to the mod, that is `D:\SteamLibrary\steamapps\workshop\content\107410\450814997` instead of `D:\SteamLibrary\steamapps\common\Arma 3\!Workshop\@CBA_A3`. The "folders" in !Workshop are actually symbolic links to actual mod locations.

I assume TADST and Serverify leave it up to the OS to resolve the path when Arma is trying to access it. Shouldn't make any difference though.

Hopefully the RPT helps to figure out what's wrong.

**Comment by pgraham1337** [comment]
Of course, glad to be of help. I'm glad that a no-BS tool like yours exists. 
Here's a .RPT that has the error.
The reason I believe it has something to do with mods, is because around line ~650, it displays the addons loaded including base game DLC. It seems all the symbolic links are read as the Steam Workshop ID instead of the actual workshop name - but I have no idea why Advanced Rappelling isn't affected by this.
I had to change the extension to .txt in order for it to upload to Git.
[arma3server_x64_2020-09-21_19-50-59.txt](https://github.com/Cambusta/Arma3-SSPSL/files/5271959/arma3server_x64_2020-09-21_19-50-59.txt)

**Comment by Cambusta** [comment]
Thanks for the file, it was really helpful! 😊

The problem turned out to be trickier than expected though. It seems that the server executable doesn't like paths with spaces in `-mod` parameter even if it's properly quoted.

I'm able to reproduce it but very inconsistently and the server doesn't really say what exactly it doesn't like about the parameters, I'll have to dig into it further.

**Comment by Cambusta** [comment]
Fixed the problem! 🎆 

Please give SSPSL an another shot, it should now run as expected for you.

The problem was actually very simple, I accidentally specified default profiles path as 
`"-profiles=<...>\Arma3SSPSL\profiles\"`
and the very last backslash before quotation mark `\"` "escaped" the quotation mark, making it disappear for the server. So all following quotations marks became mismatched and caused mod parameter parsing go haywire.

**Comment by Cambusta** [comment]
@pgraham1337 Thank you very much for your time and effort! 🤝 
If you hadn't reported the problem it would probably take me literal years to notice it by myself.

**Comment by pgraham1337** [comment]
Of course! I'm glad I was able to help you fix the problem. I will give it another shot this weekend if I find the chance to play. 😃 Thanks for your hard work.
